# @package _global_
defaults:
  - physx

simulator:
  config:
    sim:
      physx:
        use_gpu: true   # GPU PhysX; 虚拟化/云 GPU 不支持时覆盖为 false 用 CPU
        gpu_found_lost_pairs_capacity: ${eval:2**21}
        gpu_max_rigid_contact_count: ${eval:2**23}
        gpu_found_lost_aggregate_pairs_capacity: ${eval:2**25}
